habis_uts/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('story6.urls'))),
    path('story7/', include(('story7.urls'))),
    path('story8/', include(('story8.urls'))),
    path('story9/', include('story9.urls')),
]

story6/urls.py
from django.contrib import admin
from django.urls import path, include
from story6.views import index, add_status
app_name = 'story6'

urlpatterns = [
    path('', index, name='index'),
    path('add_status', add_status, name="add_status"),
]

story7/urls.py
from django.contrib import admin
from django.urls import path, include
from story7.views import profile

app_name = 'story7'
urlpatterns = [
    path('', profile, name="profile"),
]

story8/urls.py
from django.contrib import admin
from django.urls import path, include
from story8.views import index

app_name = 'story8'
urlpatterns = [
    path('', index, name="index"),
]

story9/urls.py
from django.contrib import admin
from django.urls import path, include
from story9.views import register, index
from django.contrib.auth.views import LoginView as inview
from django.contrib.auth.views import LogoutView as outview

app_name = 'story9'
outpage = 'index'
urlpatterns = [
    path('', index, name="index"),
    path('register/', register, name='register'),
    path('login/', inview.as_view(), name="login"),
    path('logout/', outview.as_view(next_page='/story9/'), name="logout")
]

story6/models.py
from django.db import models

# Create your models here.


class Status(models.Model):
    id = models.AutoField(primary_key=True)
    forms = models.CharField(max_length=200)

story7/models.py
from django.db import models

# Create your models here.

story8/models.py
from django.db import models

# Create your models here.

story9/models.py
from django.db import models

# Create your models here.

story6/forms.py
from django import forms


class Forms(forms.Form):
    status_attrs = {
        "type": "text",
        "placeholder": "Hello, how are you ?",
        "class": "search-text",
        "name": "newstatus"
    }
    status = forms.CharField(
        max_length=200, required=True, widget=forms.TextInput(attrs=status_attrs))

story9/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class RegisterForm(UserCreationForm):
    first_name = forms.CharField(max_length=30)
    last_name = forms.CharField(max_length=30)
    email = forms.EmailField(max_length=75)

    class Meta:
        model = User
        fields = ("username", "first_name", "last_name", "email",)

    def save(self, commit=True):
        user = super(RegisterForm, self).save(commit=False)
        user.first_name = self.cleaned_data["first_name"]
        user.last_name = self.cleaned_data["last_name"]
        user.email = self.cleaned_data["email"]
        if commit:
            user.save()
        return user

story6/views.py
from django.shortcuts import render
from .forms import Forms
from story6 import forms
from django.urls import reverse
from django.http import HttpResponseRedirect
from story6.models import Status


# Create your views here.


def index(request):
    response = {
        'status': Forms,
        'events': Status.objects.all()
    }
    return render(request, 'status.html', response)


def add_status(request):
    forms = Forms(request.POST)
    if request.method == "POST":
        if forms.is_valid():
            clean = forms.cleaned_data
            status = Status()
            status.forms = clean['status']
            status.save()
            print(status)
            return HttpResponseRedirect('/')
    else:
        return request, 'status.html'

story7/views.py
from django.shortcuts import render


# Create your views here.
def profile(request):
  return render(request, 'profile.html')

story8/views.py
from django.shortcuts import render
from django.http import JsonResponse

# Create your views here.


def index(request):
    return render(request, "story8.html")


def populateToSearch(request, find="minecraft"):
    link = "https://www.googleapis.com/books/v1/volumes?q=" + find
    data_final = request.get(link).json()
    return JsonResponse(data_final)

story9/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.http.response import HttpResponseRedirect
from django.contrib.auth import authenticate, logout
from story9.forms import RegisterForm

# Create your views here.


def index(request):
    return render(request, "story9.html")


@login_required
def greetings(request):
    return render(request, "greetings.html")


def register(response):
    if response.method == "POST":
        form = RegisterForm(response.POST)
        if form.is_valid():
            form.save()
            new_user = form.save()
            new_user = authenticate(
                username=response.POST['username'], password=response.POST['password1'])
            return redirect('/story9/')
    else:
        form = RegisterForm()
    return render(response, "registration/register.html", {'form': form})

story6/templates/status.html
<!DOCTYPE html> {% load static %}
<html lang="en">
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link href="https://fonts.googleapis.com/css?family=Slabo+27px&display=swap" rel="stylesheet">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

<head>
    <meta charset="UTF-8">
    <title>Hello</title>
</head>

<body>
    <h1> Hello bruh</h1>
    <form class="box" method="POST" action="{% url 'story6:add_status' %}">
        {% csrf_token %} {{ status.status }}
        <button type="submit" class="btn btn-secondary" id="submit">POST</button>
    </form>

    {% for item in events %}
    <div class="card shadow" style="margin-left:41%; width: 18rem; border-radius: 32px; padding:15px; margin-bottom:32px;">
        <div class="card-body">
            <h3 class="card-title"> {{ item.forms }} </h3>
        </div>
    </div>
    {% endfor %}

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>

</html>

story7/templates/profile.html
<!DOCTYPE html>{% load static %}
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>jQuery UI Accordion - Default functionality</title>
  <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
  <link rel="stylesheet" type="text/css" href="{% static 'story7/style.css' %}">
  <script>
  $( function() {
    $("#accordion").accordion();
    heightstyle = "content";
  } );
  </script>
</head>
<body>

<!-- Rounded switch -->
<label class="switch">
  <input id="theme" type="checkbox">
  <span class="slider round"></span>
</label>

<div id="accordion">
  <h3>Who Am I?</h3>
  <div>
    <p>
    Hi! My name is Nadia and I am a Information System Student 
    currently studying University Of Indonesia.
    </p>
  </div>
  <h3>What are my dreams?</h3>
  <div>
    <p>
    I have a dream to sleep 8 hours/day.
    </p>
  </div>
  <h3>tugas</h3>
  <div>
    <p>
    banyak
    </p>
    <ul>
      <li>ppm</li>
      <li>sda</li>
      <li>ppw</li>
    </ul>
  </div>
  <h3>Section 4</h3>
  <div>
    <p>
    Cras dictum. Pellentesque habitant morbi tristique senectus et netus
    et malesuada fames ac turpis egestas. Vestibulum ante ipsum primis in
    faucibus orci luctus et ultrices posuere cubilia Curae; Aenean lacinia
    mauris vel est.
    </p>
    <p>
    Suspendisse eu nisl. Nullam ut libero. Integer dignissim consequat lectus.
    Class aptent taciti sociosqu ad litora torquent per conubia nostra, per
    inceptos himenaeos.
    </p>
  </div>
  <script src="{% static 'story7/change_theme.js' %}"></script>
</div>
</body>
</html>

story8/templates/story8.html
{% load staticfiles %}
<html>

<head>
    <title>
        Pencarian Buku
    </title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" ntegrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="{% static 'js/library.js' %}"></script>
</head>

<body>
    <h1>Welcome! </h1>
    <h3>Find Your Favorite Book Here</h3>
    <div class='searchbar' style="width: 20rem;">
        <div class="input-group mb-3">

            <input type="text" class="form-control" id="search-query" placeholder="Search book tile or keywords">
            <div class="input-group-prepend">
                <button class="btn btn-outline-secondary" type="submit" onclick="getQuery()" id="button-addon1">Search</button>
            </div>
        </div>
    </div>
    <div class="shelf" style="margin: auto;height: 100%;width: 100%;">
        <table id="book" class="table table-hover table-responsive table-da rk" style="margin: auto;">
            <thread>
                <tr>
                    <th scope="col">Cover</th>
                    <th scope="col">Title</th>
                    <th scope="col">Author</th>
                    <th scope="col">Publisher</th>
                </tr>
            </thread>
        </table>
    </div>
</body>

story9/templates/story9.html
<!DOCTYPE html>
<html>

<head>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
</head>
<title>
    Welcome
</title>

</head>

<body>
    {% block content %} {% if user.is_authenticated%}
    <h1> Hello {{request.user.first_name}} {{request.user.last_name}}</h1>
    <a href="{% url 'story9:logout' %}"> logout </a> {% else %}
    <h1> Hello! please Login or Register down below </h1>
    <a href="{% url 'story9:login' %}"> Login </a> <br>
    <a href="{% url 'story9:register' %}"> Register </a> {% endif %} {% endblock %}
</body>